name: CD

on:
  push:
    branches: ['main']

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    if: "contains(github.event.head_commit.message, 'release')"
    name: Test
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm ci
      - run: npm test

  build-and-deploy:
    runs-on: ubuntu-latest
    if: "contains(github.event.head_commit.message, 'release')"
    needs: test
    name: Build
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - run: npm ci
      - run: npm run build
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
